language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    - antoine@sabot-durand.net
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/725c6d818aa5fd68bad2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always